-- PostgreSQL (Supabase) Database Schema

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Buses Table
CREATE TABLE IF NOT EXISTS buses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    source TEXT NOT NULL,
    destination TEXT NOT NULL,
    bus_type TEXT NOT NULL,
    fare NUMERIC(10, 2) NOT NULL,
    total_seats INTEGER DEFAULT 40,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Bookings Table
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    bus_id BIGINT NOT NULL,
    journey_date DATE NOT NULL,
    passengers INTEGER NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT DEFAULT 'Confirmed' CHECK (status IN ('Confirmed', 'Pending', 'Cancelled')),
    booking_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_bus FOREIGN KEY (bus_id) REFERENCES buses(id) ON DELETE CASCADE
);

-- Insert Default Admin
INSERT INTO users (name, email, password, role) 
VALUES ('Admin', 'admin@busgo.com', 'admin123', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Insert Dummy Bus Data
INSERT INTO buses (name, source, destination, bus_type, fare) 
VALUES 
('Shivneri Travels', 'Pune', 'Mumbai', 'A/C Seater', 400.00),
('VRL Travels', 'Mumbai', 'Nagpur', 'A/C Sleeper', 1200.00),
('Neeta Travels', 'Pune', 'Nashik', 'Non A/C Seater', 350.00),
('SRS Travels', 'Mumbai', 'Goa', 'A/C Sleeper', 1500.00);
